# Generated by Django 5.1.6 on 2025-02-22 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 3, 39, 5, 623826, tzinfo=datetime.timezone.utc)),
        ),
    ]
