# Generated by Django 5.1.6 on 2025-02-23 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0004_remove_story_image_remove_story_video_story_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 2, 48, 56, 182387, tzinfo=datetime.timezone.utc)),
        ),
    ]
