# Generated by Django 5.1.6 on 2025-02-24 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0005_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 15, 29, 40, 509564, tzinfo=datetime.timezone.utc)),
        ),
    ]
