# Generated by Django 5.1.6 on 2025-03-12 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0013_alter_story_options_story_likes_story_viewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 10, 22, 5, 773580, tzinfo=datetime.timezone.utc)),
        ),
    ]
