# Generated by Django 5.1.6 on 2025-03-20 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0014_story_caption_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 14, 34, 22, 825455, tzinfo=datetime.timezone.utc)),
        ),
    ]
