# Generated by Django 5.1.6 on 2025-03-21 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0015_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 3, 48, 7, 760199, tzinfo=datetime.timezone.utc)),
        ),
    ]
