# Generated by Django 5.1.6 on 2025-03-26 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0017_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 1, 57, 54, 381483, tzinfo=datetime.timezone.utc)),
        ),
    ]
