# Generated by Django 5.1.6 on 2025-03-27 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0019_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 5, 54, 1, 143448, tzinfo=datetime.timezone.utc)),
        ),
    ]
