# Generated by Django 5.1.6 on 2025-03-27 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0020_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 9, 16, 49, 743896, tzinfo=datetime.timezone.utc)),
        ),
    ]
