# Generated by Django 5.1.6 on 2025-03-29 03:55

import cloudinary.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0021_alter_story_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio')),
                ('duration', models.FloatField()),
                ('is_trending', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 3, 55, 5, 408591, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='story',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='story_app.musictrack'),
        ),
    ]
