# Generated by Django 5.1.6 on 2025-03-30 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0022_musictrack_alter_story_expires_at_story_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 4, 1, 11, 214363, tzinfo=datetime.timezone.utc)),
        ),
    ]
