# Generated by Django 5.1.6 on 2025-04-11 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0023_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 9, 32, 7, 892659, tzinfo=datetime.timezone.utc)),
        ),
    ]
