# Generated by Django 5.1.6 on 2025-04-16 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0024_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 13, 27, 45, 528191, tzinfo=datetime.timezone.utc)),
        ),
    ]
