# Generated by Django 5.1.6 on 2025-04-17 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0025_alter_story_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='start_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 4, 27, 52, 503268, tzinfo=datetime.timezone.utc)),
        ),
    ]
