# Generated by Django 5.1.6 on 2025-04-28 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0027_alter_story_expires_at_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 3, 54, 33, 790856, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 3, 54, 19, 6515, tzinfo=datetime.timezone.utc)),
        ),
    ]
