# Generated by Django 5.1.6 on 2025-04-28 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0028_livestream_ended_at_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 4, 21, 1, 781453, tzinfo=datetime.timezone.utc)),
        ),
    ]
