# Generated by Django 5.1.6 on 2025-04-29 08:50

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0029_alter_livestream_ended_at_alter_story_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='recording_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='stream_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 8, 50, 20, 914719, tzinfo=datetime.timezone.utc)),
        ),
    ]
