# Generated by Django 5.1.6 on 2025-05-12 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0030_livestream_recording_url_livestream_stream_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 52, 27, 410664, tzinfo=datetime.timezone.utc)),
        ),
    ]
