# Generated by Django 5.1.6 on 2025-05-13 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0033_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 9, 51, 46, 702053, tzinfo=datetime.timezone.utc)),
        ),
    ]
