# Generated by Django 5.1.6 on 2025-05-13 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0034_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 11, 13, 15, 884795, tzinfo=datetime.timezone.utc)),
        ),
    ]
