# Generated by Django 5.1.6 on 2025-05-15 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0035_alter_story_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 10, 18, 9, 884860, tzinfo=datetime.timezone.utc)),
        ),
    ]
