GET http://127.0.0.1:8000/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjAwMTAzLCJpYXQiOjE3NDAxOTY1MDMsImp0aSI6IjkxZjIwMDIyYzkzNjQ0NmJiYzcxNWQyZGI5ZTNhNGQ0IiwidXNlcl9pZCI6ImZkNTRhNDM4LTMzOWYtNDFiMi1iYmM2LWQyZGZkZDQ2MmIzYyJ9.i7le9X0GIw4fvuRpPoAl3uN5q61bAtqsttW5P573hLE


###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "usop",
    "password" : "usop@123"
}

###
PUT http://127.0.0.1:8000/users/fd54a438-339f-41b2-bbc6-d2dfdd462b3c/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjAwMTAzLCJpYXQiOjE3NDAxOTY1MDMsImp0aSI6IjkxZjIwMDIyYzkzNjQ0NmJiYzcxNWQyZGI5ZTNhNGQ0IiwidXNlcl9pZCI6ImZkNTRhNDM4LTMzOWYtNDFiMi1iYmM2LWQyZGZkZDQ2MmIzYyJ9.i7le9X0GIw4fvuRpPoAl3uN5q61bAtqsttW5P573hLE


{
    "username" : "usop",
    "password" : "usop@123",
    "last_name" : "hero"
}

