# Generated by Django 5.1.6 on 2025-04-17 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsreport',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='data_type',
            field=models.CharField(choices=[('users', 'Users'), ('posts', 'Posts'), ('likes', 'Likes'), ('comments', 'Comments'), ('hashtags', 'Hashtags')], default='users', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='generated_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
