# Generated by Django 5.1.6 on 2025-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'is_verified'), ('username', 'is_verified')},
        ),
    ]
