# Generated by Django 5.1.6 on 2025-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_signIn',
            field=models.BooleanField(default=False),
        ),
    ]
