# Generated by Django 5.1.6 on 2025-02-23 02:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='gif_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
        migrations.RemoveField(
            model_name='message',
            name='voice_note',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
