# Generated by Django 5.1.6 on 2025-03-26 01:57

import chat_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_remove_message_gif_url_remove_message_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='encryption_key',
            field=models.CharField(default=chat_app.models.generate_encryption_key, max_length=64),
        ),
    ]
