# Generated by Django 5.1.6 on 2025-03-20 14:34

import chat_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_remove_message_gif_url_remove_message_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='encryption_key_salt',
            field=models.CharField(default=chat_app.models.generate_encryption_key_salt, max_length=32),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
