# Generated by Django 5.1.6 on 2025-03-29 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_chatroom_last_message_at_chatroom_unread_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
    ]
