# Generated by Django 5.1.6 on 2025-03-31 16:39

from django.db import migrations
from cryptography.fernet import Fernet

def fix_encryption_keys(apps, schema_editor):
    ChatRoom = apps.get_model('chat_app', 'ChatRoom')
    for room in ChatRoom.objects.all():
        room.encryption_key = Fernet.generate_key().decode()
        room.save()

class Migration(migrations.Migration):
    dependencies = [('chat_app', '0009_chatroom_last_message_at_message_is_deleted_and_more')]
    operations = [migrations.RunPython(fix_encryption_keys)]