# Generated by Django 5.1.6 on 2025-04-03 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0013_chatroom_admin_chatroom_last_message_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
       
    ]
