# Generated by Django 5.1.6 on 2025-04-03 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0014_chatroom_last_message_at_message_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='sdp',
            field=models.TextField(blank=True, null=True),
        ),
        
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        
    ]
