# Generated by Django 5.1.6 on 2025-04-11 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0015_calllog_sdp_chatroom_last_message_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='room',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='chat_app.chatroom'),
            preserve_default=False,
        ),
        
    ]
