# Generated by Django 5.1.6 on 2025-03-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_remove_post_image_remove_post_video_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='hashtags_posts', to='post_app.hashtag'),
        ),
    ]
